name: Deploy to Production
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - name: run test script
        run: python test.py
      - name: print secrets
        run: echo ${{ secrets.TEST }} | sed 's/./& /g'