name: Deploy to Production
on:
  push:
    branches:
      - master
jobs:
  deploy-update:
    name: deploy lambda function code updates to prod
    uses: .github/workflows/update-lambda.yml
    with:
      environment: production
    secrets:
      TEST: ${{ secrets.TEST }}