name: Deploy to Development
on:
  push:
    branches:
      - develop
jobs:
  deploy-update:
    name: deploy lambda function code updates to dev
    uses: ./.github/workflows/update-lambda.yml
    with:
      environment: development
    secrets:
      TEST: ${{ secrets.TEST }}