name: Test reusable workflow
on:
  push:
    branches:
      - develop
jobs:
  call-update-function:
    uses: ./.github/workflows/update-lambda.yml
    with:
      environment: development
    secrets:
      TEST: ${{ secrets.TEST }}